const AUDIT_CRITICALITY = Object.freeze({ CRITICAL: 'CRITICAL', BEST_EFFORT: 'BEST_EFFORT' });

const AUDIT_ACTIONS = Object.freeze({
  // FASE 1: Críticas Originales
  DOCUMENTO_ARCHIVADO:   { code: 'DOCUMENTO_ARCHIVADO',   criticality: AUDIT_CRITICALITY.CRITICAL },
  APROBAR_PRESUPUESTO:   { code: 'APROBAR_PRESUPUESTO',   criticality: AUDIT_CRITICALITY.CRITICAL },
  LOGIN_EXITOSO:         { code: 'LOGIN_EXITOSO',         criticality: AUDIT_CRITICALITY.CRITICAL },
  LOGIN_FALLIDO:         { code: 'LOGIN_FALLIDO',         criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  DASHBOARD_VISUALIZADO: { code: 'DASHBOARD_VISUALIZADO', criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  
  // USUARIOS
  LOGIN_GOOGLE:          { code: 'LOGIN_GOOGLE',          criticality: AUDIT_CRITICALITY.CRITICAL },
  CREACION_USUARIO:      { code: 'CREACION_USUARIO',      criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  ACTUALIZACION_USUARIO: { code: 'ACTUALIZACION_USUARIO', criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  ELIMINACION_USUARIO:   { code: 'ELIMINACION_USUARIO',   criticality: AUDIT_CRITICALITY.CRITICAL },
  CAMBIO_ESTADO_USUARIO: { code: 'CAMBIO_ESTADO_USUARIO', criticality: AUDIT_CRITICALITY.CRITICAL },
  
  // EVENTOS
  CREACION_EVENTO:       { code: 'CREACION_EVENTO',       criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  EDICION_EVENTO:        { code: 'EDICION_EVENTO',        criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  ACTUALIZACION_EVENTO:  { code: 'ACTUALIZACION_EVENTO',  criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  ELIMINACION_EVENTO:    { code: 'ELIMINACION_EVENTO',    criticality: AUDIT_CRITICALITY.CRITICAL },
  AUTO_FINALIZACION_EVENTO: { code: 'AUTO_FINALIZACION_EVENTO', criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  
  // FINANZAS Y POA
  CREACION_POA:          { code: 'CREACION_POA',          criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  ACTUALIZACION_POA:     { code: 'ACTUALIZACION_POA',     criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  ALERTA_POA_20:         { code: 'ALERTA_POA_20',         criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  OBSERVACION_PRESUPUESTO:{ code: 'OBSERVACION_PRESUPUESTO',criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  SUBIDA_EVIDENCIA_CONTABLE:{code: 'SUBIDA_EVIDENCIA_CONTABLE',criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  ELIMINACION_EVIDENCIA_CONTABLE:{code: 'ELIMINACION_EVIDENCIA_CONTABLE',criticality: AUDIT_CRITICALITY.CRITICAL },

  // CATALOGOS
  CREACION_CATALOGO:     { code: 'CREACION_CATALOGO',     criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  ACTUALIZACION_CATALOGO:{ code: 'ACTUALIZACION_CATALOGO',criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  ELIMINACION_CATALOGO:  { code: 'ELIMINACION_CATALOGO',  criticality: AUDIT_CRITICALITY.CRITICAL },
  CREACION_AUDIOVISUAL:  { code: 'CREACION_AUDIOVISUAL',  criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  ACTUALIZACION_AUDIOVISUAL: { code: 'ACTUALIZACION_AUDIOVISUAL', criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  ACTUALIZACION_AUDIOVISUAL_GLOBAL: { code: 'ACTUALIZACION_AUDIOVISUAL_GLOBAL', criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  
  // DOCUMENTOS Y LEGAL
  SUBIDA_DOCUMENTO_BOVEDA:{code: 'SUBIDA_DOCUMENTO_BOVEDA',criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  RESOLUCION_LEGAL:       { code: 'RESOLUCION_LEGAL',      criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  CIERRE_EXPEDIENTE:      { code: 'CIERRE_EXPEDIENTE',     criticality: AUDIT_CRITICALITY.CRITICAL },
  APERTURA_FLUJO_LEGAL:   { code: 'APERTURA_FLUJO_LEGAL',  criticality: AUDIT_CRITICALITY.BEST_EFFORT },

  // SERVICIOS EXTERNOS Y PROVEEDORES
  SOLICITUD_SERVICIO_EXTERNO: { code: 'SOLICITUD_SERVICIO_EXTERNO', criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  ACTUALIZACION_SERVICIO_EXTERNO: { code: 'ACTUALIZACION_SERVICIO_EXTERNO', criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  ELIMINACION_SERVICIO_EXTERNO: { code: 'ELIMINACION_SERVICIO_EXTERNO', criticality: AUDIT_CRITICALITY.CRITICAL },
  ENVIO_ORDEN_PROVEEDOR:  { code: 'ENVIO_ORDEN_PROVEEDOR', criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  RECEPCION_SERVICIO:     { code: 'RECEPCION_SERVICIO',    criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  PAGO_SERVICIO:          { code: 'PAGO_SERVICIO',         criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  ACTUALIZACION_PROVEEDOR:{ code: 'ACTUALIZACION_PROVEEDOR',criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  CAMBIO_ESTADO_PROVEEDOR:{ code: 'CAMBIO_ESTADO_PROVEEDOR',criticality: AUDIT_CRITICALITY.CRITICAL },
  PAGO_FACTURA_B2B:       { code: 'PAGO_FACTURA_B2B',      criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  CREACION_PROVEEDOR:     { code: 'CREACION_PROVEEDOR',    criticality: AUDIT_CRITICALITY.CRITICAL },
  SUBIDA_COTIZACION:      { code: 'SUBIDA_COTIZACION',     criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  EVALUACION_COTIZACION:  { code: 'EVALUACION_COTIZACION', criticality: AUDIT_CRITICALITY.CRITICAL },
  ADJUDICACION_LICITACION:{ code: 'ADJUDICACION_LICITACION', criticality: AUDIT_CRITICALITY.CRITICAL },
  EDICION_ORDEN_COMPRA:   { code: 'EDICION_ORDEN_COMPRA', criticality: AUDIT_CRITICALITY.CRITICAL },

  // CRONOGRAMA Y ORGANIZADORES
  ASIGNACION_ORGANIZADOR: { code: 'ASIGNACION_ORGANIZADOR',criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  REMOCION_ORGANIZADOR:   { code: 'REMOCION_ORGANIZADOR',  criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  CREACION_TAREA_CRONOGRAMA:{code: 'CREACION_TAREA_CRONOGRAMA',criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  ACTUALIZACION_TAREA_CRONOGRAMA:{code: 'ACTUALIZACION_TAREA_CRONOGRAMA',criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  ELIMINACION_TAREA_CRONOGRAMA:{code: 'ELIMINACION_TAREA_CRONOGRAMA',criticality: AUDIT_CRITICALITY.CRITICAL },
  RESOLUCION_INCIDENCIA_LOGISTICA:{code:'RESOLUCION_INCIDENCIA_LOGISTICA',criticality: AUDIT_CRITICALITY.BEST_EFFORT },

  // ACCIONES ADICIONALES
  ACTUALIZAR_OC_SERVICIO: { code: 'ACTUALIZAR_OC_SERVICIO', criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  DICTAMEN_LEGAL:         { code: 'DICTAMEN_LEGAL',         criticality: AUDIT_CRITICALITY.BEST_EFFORT },
  DICTAMEN_LEGAL_ACTUALIZADO: { code: 'DICTAMEN_LEGAL_ACTUALIZADO', criticality: AUDIT_CRITICALITY.BEST_EFFORT }
});

function validateAction(accion) {
  if (!accion || !accion.code || !accion.criticality) throw new Error('Formato de acción inválido');
  const match = AUDIT_ACTIONS[accion.code];
  if (!match) {
    throw new Error(`Acción alterada o no registrada formalmente en el diccionario: ${accion.code}`);
  }
  if (match.criticality !== accion.criticality) throw new Error(`Críticidad alterada: ${accion.code}`);
}

module.exports = { AUDIT_ACTIONS, AUDIT_CRITICALITY, validateAction };
